### ISSUE TITLE
2 Создайте тест для https://petstore.swagger.io/#/user/createUser используя подход с dto и генерацией случайных данных.

### ISSUE THREAD

**Issue by tallinn-learning** [Yaroslav3390/Homework11#1]
https://github.com/Yaroslav3390/Homework11/blob/6d54b591e020d45e0c8ba51fe0758070b7cc0f54/src/test/java/org/example/PetStoreAPI.java#L3

**Comment by Yaroslav3390** [comment]
Я его в другом классе написал) перенес в PetStoreAPI, https://github.com/Yaroslav3390/Homework11/blob/master/src/test/java/org/example/PetStoreAPI.java
